# Generated by Django 2.0.13 on 2019-05-07 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('identifier', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to='menus/images/')),
                ('status', models.PositiveSmallIntegerField()),
                ('has_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'menu_items',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('background', models.FileField(blank=True, null=True, upload_to='menus/backgrounds/')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.Template')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.Menu'),
        ),
    ]
