# Generated by Django 2.0.13 on 2019-05-07 22:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('name', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to='menus/images/')),
                ('status', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.Menu')),
            ],
            options={
                'db_table': 'menu_slots',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
