# Generated by Django 2.0.13 on 2019-04-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='background',
            field=models.FileField(default=None, upload_to='templates/backgrounds/'),
            preserve_default=False,
        ),
    ]
