# Generated by Django 2.0.13 on 2019-04-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_background'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='description',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='menu',
            name='background',
            field=models.FileField(null=True, upload_to='templates/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='template',
            field=models.FileField(null=True, upload_to='templates/menus/'),
        ),
    ]
